-- 1 PASSO: CRIAR A BASE DE DADOS (DATABASE OU SCHEMA)
create database if not exists PROVA_CC1MC;
-- CRIAR DATABASE OU SCHEMA [IF NOT EXISTS] NOME;
-- IF NOT EXISTS: SE JÁ ESXISTIR, NÃO CRIE;

-- 2 PASSO; ABRR A BASE DADOS PARA USO
use PROVA_CC1MC;
-- USE NOME_BASE_DE_DADOS;

-- 3 PASSO; CRIAR AS TABELAS SEM CHAVE ESTRANGEIRA
create table if not exists CLIENTES(
--NOME ATRIBUTO
NUM_CLIENTE INT primary KEY,
NOME VARCHAR(100) NOT NULL,
RUA_CLIENTE VARCHAR(100) NOT NULL,
NUMERO_RUA_CLIENTE INT,
BAIRRO CLIENTE VARCHAR(100) NOT NULL, 
CIDADE_CLIENTE VARCHAR(100) NOT NULL,
UF_CLIENTE CHAR(2) NOT NULL,
CEP_CLIENTE VARCHAR(9) NOT NULL);

create table if not exists CARRO(
ID_CARRO int primary key,
REGISTO varchar(20) not null,
MARCA varchar(20) not null);

-- 4 PASSO: CRIAR TABELAS COM FK, POR ORDEM NECESSARIA
create table if not exists APOLICES(
NUM_APLO int primary key,
VALOR_APOL decimal(10,2) not null,
CLIENTE int not null,
CARRO int not null,
constraint CLI_APO foreign key(CLIENTE) REFERENCES CLIENTES(NUM_CLIENTES),
constraint CAR_APO foreign key(CARRO) references CARROS(ID_CARRO));

Create table if not exists ACIDENTES(
ID_ACIDENTE INT auto_increment primary KEY,
DATA_ACIDENTE DATE NOT NULL,
HORA_ACIDENTE TIME NOT NULL,
RUA_ACID VARCHAR(100) NOT NULL,
NUMR_ACID INT,
BAIRRO_ACID VARCHAR(100) NOT NULL,
CIDADE_ACID VARCHAR(100) NOT NULL,
UF_ACID char(2),
CEP_ACID VARCHAR(9),
CLIENTE INT NOT NULL,
constraint CLI_ACI foreign key (CLIENTE) references CLIENTE(NUM_CLIENTE)
);