-- 1 PASSO: CRIAR A BASE DE DADOS (DATABASE OU SCHEMA):
CREATE DATABASE IF NOT EXISTS PROVA_CC1MC;
-- CRIAR DATABASE OU SCHEMA [IF NOT EXISTS] NOME;
-- IF NOT EXISTS: SE JÁ EXISTIR, NÃO CRIE;

-- 2 PASSO: ABRIR A BASE DADOS PRA USO
USE PROVA_CC1MC;
-- USE NOME_BASE_DE_DADOS;

-- 3 PASSO: CRIAR AS TABELAS SEM CHAVE ESTRANGEIRA
 CREATE TABLE IF NOT EXISTS CLIENTES(
 -- NOME_ATRIBUTO TIPO [RESTRIÇÃO]
 NUM_CLIENTE INT PRIMARY KEY,
 NOME_CLIENTE VARCHAR(100) NOT NULL,
 RUA_CLIENTE VARCHAR(100) NOT NULL,
 NUM_RUA_CLIENTE INT,
 BAIRRO_CLIENTE VARCHAR(100) NOT NULL,
 CIDADE_CLIENTE VARCHAR(100) NOT NULL,
 UF_CLIENTE CHAR(2) NOT NULL,
 CEP_CLIENTE VARCHAR(9) NOT NULL);
 
 CREATE TABLE IF NOT EXISTS CARROS(
 ID_CARRO INT PRIMARY KEY,
 REGISTRO VARCHAR(20) NOT NULL,
 MARCA VARCHAR(20) NOT NULL );
 
 -- 4 PASSO: CRIAR AS TABELAS COM FK, POR ORDEM DE NECESSIDADE
CREATE TABLE IF NOT EXISTS APOLICES(
NUM_APOL INT,
VALOR_APOL DECIMAL(10,2) NOT NULL,
CLIENTE INT NOT NULL,
CARRO INT NOT NULL,
PRIMARY KEY(NUM_APOL),
CONSTRAINT CLI_APO FOREIGN KEY(CLIENTE) REFERENCES
CLIENTES(NUM_CLIENTE),
CONSTRAINT CAR_APO FOREIGN KEY(CARRO) REFERENCES
CARROS(ID_CARRO));

CREATE TABLE IF NOT EXISTS ACIDENTES(
ID_ACID INT AUTO_INCREMENT PRIMARY KEY,
DATA_ACID DATE NOT NULL,
HORA_ACID TIME NOT NULL,
RUA_ACID VARCHAR(100) NOT NULL,
NUMR_ACID INT,
BAIRRO_ACID VARCHAR(100) NOT NULL,
CIDADE_ACID VARCHAR(100) NOT NULL,
UF_ACID CHAR(2),
CEP_ACID VARCHAR(9),
CLIENTE INT NOT NULL,
CONSTRAINT CLI_ACI FOREIGN KEY (CLIENTE) REFERENCES
CLIENTES(NUM_CLIENTE)
);